name: 'mulesoft-build-action'
description: 'action responsible to build mule projects'
author: 'Faisal Khanani'

inputs:
  release-tag:
    description: 'release number to be build'
    required: true
  test-args:
    description: 'Json object'
    required: false
    default: "{}"    
    
runs:
  using: 'node12'
  main: 'dist/index.js'
